In [ ]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json

{'kaggle.json': b'{"username":"titanjd","key":"13a24d9a0251f2dbe716b6e90c2431e4"}'}

In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [48]:
!kaggle datasets download teejmahal20/airline-passenger-satisfaction

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.0), please consider upgrading to the latest version (2.0.1)
Dataset URL: https://www.kaggle.com/datasets/teejmahal20/airline-passenger-satisfaction
License(s): other
Downloading airline-passenger-satisfaction.zip to /content
100% 2.71M/2.71M [00:00<00:00, 99.5MB/s]

In [50]:
import zipfile
import os

# Specify the name of the downloaded zip file (e.g., 'titanic.zip')
zip_file_name = 'airline-passenger-satisfaction.zip'

# Create a directory for the extracted files
destination_dir = '/content/dataset_files'
os.makedirs(destination_dir, exist_ok=True)

# Unzip the file
with zipfile.ZipFile(zip_file_name, 'r') as zip_ref:
    zip_ref.extractall(destination_dir)

# (Optional) Remove the zip file after extraction
os.remove(zip_file_name)

# List the extracted files
print(f"Extracted files: {os.listdir(destination_dir)}")

Extracted files: ['train.csv', 'test.csv']

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [61]:
df = pd.read_csv('/content/dataset_files/train.csv')
df.head()

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,0,70172,Male,Loyal Customer,13,Personal Travel,Eco Plus,460,3,4,...,5,4,3,4,4,5,5,25,18.0,neutral or dissatisfied
1,1,5047,Male,disloyal Customer,25,Business travel,Business,235,3,2,...,1,1,5,3,1,4,1,1,6.0,neutral or dissatisfied
2,2,110028,Female,Loyal Customer,26,Business travel,Business,1142,2,2,...,5,4,3,4,4,4,5,0,0.0,satisfied
3,3,24026,Female,Loyal Customer,25,Business travel,Business,562,2,5,...,2,2,5,3,1,4,2,11,9.0,neutral or dissatisfied
4,4,119299,Male,Loyal Customer,61,Business travel,Business,214,3,3,...,3,3,4,4,3,3,3,0,0.0,satisfied

In [62]:
df.satisfaction.unique()

array(['neutral or dissatisfied', 'satisfied'], dtype=object)

In [63]:
df.shape

(103904, 25)

In [64]:
df = pd.get_dummies(df, drop_first=True, dtype='int16')
df.head()

,Unnamed: 0,id,Age,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,Food and drink,Online boarding,...,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,Gender_Male,Customer Type_disloyal Customer,Type of Travel_Personal Travel,Class_Eco,Class_Eco Plus,satisfaction_satisfied
0,0,70172,13,460,3,4,3,1,5,3,...,5,5,25,18.0,1,0,1,0,1,0
1,1,5047,25,235,3,2,3,3,1,3,...,4,1,1,6.0,1,1,0,0,0,0
2,2,110028,26,1142,2,2,2,2,5,5,...,4,5,0,0.0,0,0,0,0,0,1
3,3,24026,25,562,2,5,5,5,2,2,...,4,2,11,9.0,0,0,0,0,0,0
4,4,119299,61,214,3,3,3,3,4,5,...,3,3,0,0.0,1,0,0,0,0,1

In [67]:
X = df.drop(columns=['Unnamed: 0', 'id', 'satisfaction_satisfied'], axis=1)
y = df['satisfaction_satisfied']

In [68]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [69]:
# Random forests
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(max_depth=5)
model.fit(X_train, y_train)

RandomForestClassifier(max_depth=5)

In [70]:
y_pred = model.predict(X_test)

In [71]:
# classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.92      0.94      0.93     11713
           1       0.92      0.90      0.91      9068

    accuracy                           0.92     20781
   macro avg       0.92      0.92      0.92     20781
weighted avg       0.92      0.92      0.92     20781

In [49]:
!rm -rf dataset_files/