In [ ]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json

{'kaggle.json': b'{"username":"titanjd","key":"13a24d9a0251f2dbe716b6e90c2431e4"}'}

In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [31]:
!kaggle datasets download iammustafatz/diabetes-prediction-dataset

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.0), please consider upgrading to the latest version (2.0.1)
Dataset URL: https://www.kaggle.com/datasets/iammustafatz/diabetes-prediction-dataset
License(s): copyright-authors
Downloading diabetes-prediction-dataset.zip to /content
100% 734k/734k [00:00<00:00, 110MB/s]

In [32]:
import zipfile
import os

# Specify the name of the downloaded zip file (e.g., 'titanic.zip')
zip_file_name = 'diabetes-prediction-dataset.zip'

# Create a directory for the extracted files
destination_dir = '/content/dataset_files'
os.makedirs(destination_dir, exist_ok=True)

# Unzip the file
with zipfile.ZipFile(zip_file_name, 'r') as zip_ref:
    zip_ref.extractall(destination_dir)

# (Optional) Remove the zip file after extraction
os.remove(zip_file_name)

# List the extracted files
print(f"Extracted files: {os.listdir(destination_dir)}")

Extracted files: ['diabetes_prediction_dataset.csv']

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [33]:
df = pd.read_csv('/content/dataset_files/diabetes_prediction_dataset.csv')
df.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0

In [34]:
df.shape

(100000, 9)

In [36]:
df.smoking_history.unique()

array(['never', 'No Info', 'current', 'former', 'ever', 'not current'],
      dtype=object)

In [37]:
df = pd.get_dummies(df, drop_first=True, dtype='int16')

In [38]:
df.head()

,age,hypertension,heart_disease,bmi,HbA1c_level,blood_glucose_level,diabetes,gender_Male,gender_Other,smoking_history_current,smoking_history_ever,smoking_history_former,smoking_history_never,smoking_history_not current
0,80.0,0,1,25.19,6.6,140,0,0,0,0,0,0,1,0
1,54.0,0,0,27.32,6.6,80,0,0,0,0,0,0,0,0
2,28.0,0,0,27.32,5.7,158,0,1,0,0,0,0,1,0
3,36.0,0,0,23.45,5.0,155,0,0,0,1,0,0,0,0
4,76.0,1,1,20.14,4.8,155,0,1,0,1,0,0,0,0

In [40]:
from sklearn.preprocessing import MinMaxScaler
bmi_scaler = MinMaxScaler()
age_scaler = MinMaxScaler()
hba1c_level = MinMaxScaler()
blood_glucose_level = MinMaxScaler()
df['bmi'] = bmi_scaler.fit_transform(df[['bmi']])
df['age'] = age_scaler.fit_transform(df[['age']])
df['HbA1c_level'] = hba1c_level.fit_transform(df[['HbA1c_level']])
df['blood_glucose_level'] = blood_glucose_level.fit_transform(df[['blood_glucose_level']])

In [42]:
imp_cols = df.columns.to_list()
imp_cols.remove('diabetes')

In [43]:
X = df.loc[:, imp_cols]
y = df['diabetes']

In [44]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [45]:
# SVM
from sklearn.svm import SVC
model = SVC()
model.fit(X_train, y_train)

SVC()

In [46]:
y_pred = model.predict(X_test)

In [47]:
# classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98     18292
           1       0.97      0.55      0.70      1708

    accuracy                           0.96     20000
   macro avg       0.96      0.77      0.84     20000
weighted avg       0.96      0.96      0.96     20000

In [30]:
!rm -rf /content/dataset_files